name = "algo-benchmarks"
type = "javascript"
workers_dev = true
compatibility_date = "2021-08-27" # required
compatibility_flags = [ "formdata_parser_supports_files" ] # required

[vars]
WORKERS_RS_VERSION = "0.0.4"

[build]
command = "cargo install -q worker-build && worker-build --release"

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

[env.staging]
[env.stagin.build]
command = ""
[env.stagin.build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[env.production]
[env.production.build]
command = ""
[env.production.build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"
