name = "api"
type = "javascript"
account_id = "ba6c25249cb99a0248f0022ec28ac07b"
workers_dev = true

# Enable a kv-namespace to use the KV caching feature
#
# kv-namespaces = [
#   { binding = "WORKERS_GRAPHQL_CACHE", id = "" }
# ]

[build]
command = "webpack || npm run build"

[build.upload]
format = "service-worker"

[env.staging]
workers_dev = true

[env.production]
workers_dev = true

