name = "api"
type = "javascript"
workers_dev = false

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"

[env.staging]
workers_dev = true

[env.production]
workers_dev = false
