name: Deploy to Cloudflare Workers (production)

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Publish Rust/WASM GraphQL API 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: cargo
      - run: cargo install -q worker-build && worker-build --release
        working-directory: 'api'
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ env.ENVIRONMENT }}
          workingDirectory: 'api'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}