name: Deploy to Cloudflare Workers (staging)

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
        working-directory: api

      - name: Publish Rust WASM Workers 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: cargo
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          workingDirectory: 'core/algo_benchmarks'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Publish GraphQL API
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'staging'
          workingDirectory: 'api'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}